### ISSUE TITLE
Would using edlib be interesting option?

### ISSUE THREAD

**Issue by Martinsos** [ka-weihe/fastest-levenshtein#1]
Hi,
great job on the library! Especially on using js implementation for shorter strings, that is they way to go I believe.

I am author of https://github.com/Martinsos/edlib, which is implementation of Myers in C++, same as yours, and is well-featured and optimized after years of usage. However, it supports only single-char strings for now, although that is not so hard to add and might be added in next couple of months.
Anyway, I just wanted to point this out in case you find it useful, maybe it would make sense to use edlib in your library, and if not, you might find some useful bits in the code!

Edlib also has python binding/package which is well used I believe, and 3 years ago I also made node package (node-edlib), similar to yours, but I never put enough work into it to make it well suited for all sizes of sequences, as you did in your library, and it did not take off (nor would I recommend anybody to use it at the moment, next to other alternatives).

Keep up the good work!

**Comment by ka-weihe** [comment]
Thank you for the kind words! I'll definitely consider using edlib if it proves to be the same speed or faster than my implementation of Myers. I've not had time to work on this for a while, but I will soon upgrade the JS used for shorter strings (to a much faster version), and then I will look into using edlib.

Keep up the good work with edlib!

**Comment by Martinsos** [comment]
Awesome, and thanks! Just be aware of what I mentioned, that edlib does not support complex characters yet -> I would wait for that to be implemented, if I was you. good luck, closing the isssue!
