### ISSUE TITLE
If distance value same with 0 at closest function

### ISSUE THREAD

**Issue by fatawasd-dev** [ka-weihe/fastest-levenshtein#21]
If dist == 0 mean that exact value, why not return that value if dist == 0 ?
`const dist = distance(str, arr[i]); `
`if (dist === 0) return arr[i]`
`if (dist < min_distance) { `

https://github.com/ka-weihe/fastest-levenshtein/blob/37bd0917de8347c73d67467bd1c5ea803cba5f94/mod.ts#L133-L134

**Comment by ka-weihe** [comment]
It is a double-edged sword. It is undoubtedly faster if `dist` ever becomes zero, but it will be slower if it does not. It is probably better that people do this optimization in their code rather than propagate it to everyone. If they think the likelihood of `dist` becoming 0 is high enough.
