### ISSUE TITLE
Distance is always 11

### ISSUE THREAD

**Issue by muuvmuuv** [ka-weihe/fastest-levenshtein#23]
I am not like that into math, but it seems not correct for me that in this example, the levenshtein always produces 11. At least one of them matches way better than the others. What do I miss?

Repl: https://replit.com/@muuvmuuv/fastest-levenshtein#index.js

**Comment by ka-weihe** [comment]
It is correct

**Comment by muuvmuuv** [comment]
Oh ok, not very explenatory. I thought the algo is all about getting the nearest distance but in my example it doesnt feel like that. So then its just the wrong algo? Do you know which one would fit better for my needs?

**Comment by ka-weihe** [comment]
All of the strings require 11 edits (insert/replace/delete) to become "/app/me/activities". The algo does find the nearest edit distance.
