### ISSUE TITLE
User-Assigned Costs for Insertions, Substitutions, and Deletions

### ISSUE THREAD

**Issue by darnjo** [ka-weihe/fastest-levenshtein#26]
Enjoying the library so far. 

One thing that might be nice would be to allow users to assign costs to each operation. For example, substitutions and insertions might have a cost of 1 and deletions a cost of 2.

**Comment by ka-weihe** [comment]
Hey there!

Appreciate the suggestion, but unfortunately, tweaking the algorithm that way isn't quite doable at the moment. It's super specialized, so any major changes would be quite the task. Thanks for understanding!

Take care!
