### ISSUE TITLE
Please improve IE11 support or a build for browser targets

### ISSUE THREAD

**Issue by alfredriesen** [ka-weihe/fastest-levenshtein#4]
We are using fast-levenshtein on clientside. Due to your intergration into this lib, we are not able to build the app for "classic" browsers (ie11). In our webpack-build process we are already transpiling some other libs. But this one throws an error related to commonjs exports syntax: [
<img width="643" alt="Bildschirmfoto 2020-08-17 um 16 05 03" src="https://user-images.githubusercontent.com/1764527/90405011-7b3b5b00-e0a3-11ea-8959-85a3abb49b23.png">
](url)

Here is our webpack babel config:
``
                test: /\.js$/,
                exclude: /node_modules\/(?!(vuetify|fastest-levenshtein)\/).*/,
                loader: 'babel-loader',
                options: {
                    cacheDirectory: true,
                    presets: [
                        [
                            '@babel/preset-env',
                            {
                                debug: false,
                                modules: false,
                                targets: {
                                    browsers: [
                                        '> 1%',
                                        'last 2 versions',
                                        'Firefox ESR',
                                    ],
                                },
                                useBuiltIns: 'usage',
                                corejs: 3,
                            },
                        ],
                    ],
                },
``

Any suggestions?

**Comment by ka-weihe** [comment]
Thank you for the issue, I will try to fix it today with UMD.

**Comment by alfredriesen** [comment]
With an additional config options for babel I solved my problem: sourceType: 'unambiguous'! -> [https://babeljs.io/docs/en/options#sourcetype](https://babeljs.io/docs/en/options#sourcetype)

Thank you.
