### ISSUE TITLE
Inaccurate results

### ISSUE THREAD

**Issue by mustafa0x** [ka-weihe/fastest-levenshtein#5]
`closest('hello', ['relloy'], ['helloy'])` = says relloy is closer while, of course, helloy is.

See: https://svelte.dev/repl/59d7707746b34e079713c0d439121e33?version=3.24.1

**Comment by ka-weihe** [comment]
You are using it incorrectly. `closest` takes two arguments, not three. 

closest('hello', ['relloy', 'helloy'])

**Comment by mustafa0x** [comment]
@ka-weihe Right, sorry, just noticed that! Thanks!
