### ISSUE TITLE
Damerau–Levenshtein distance?

### ISSUE THREAD

**Issue by leeoniya** [ka-weihe/fastest-levenshtein#7]
hi @ka-weihe,

does/can this implementation treat transposition as a single-cost op?

https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance

**Comment by ka-weihe** [comment]
No, this implementation is not Damerau. However, the implementation can be changed to measure the Damerau Levenshtein distance instead, but that is not the scope of this package. I may create a separate package for Damerau Levenshtein in the future, but it will never be a part of this package.

**Comment by BeLi4L** [comment]
I'm also interested in a Damereau-Levenshtein variant. How would you adapt the existing algorithm for that? :thinking: 

Besides, do you have any explanation/documentation/resource to explain the current "Myers 32/X" algorithms?

**Comment by ka-weihe** [comment]
> 'm also interested in a Damereau-Levenshtein variant. How would you adapt the existing algorithm for that? thinking

A Damereau-Levenshtein variant would be trivial. I'll probably make another repo for that (soon). 

> Besides, do you have any explanation/documentation/resource to explain the current "Myers 32/X" algorithms?

No

**Comment by bestknighter** [comment]
So, is there an implementation for the Damereau-Levenshtein yet?

I tried to modify this by myself but I can't understand the logic well enough to make sure I can correctly change it, let alone to do it without taking performance hits.

**Comment by forivall** [comment]
> A Damereau-Levenshtein variant would be trivial. I'll probably make another repo for that (soon).

Did that happen? I dont see a relevant repo on your account 😢
