### ISSUE TITLE
Supported node versions

### ISSUE THREAD

**Issue by stof** [ka-weihe/fastest-levenshtein#9]
Currently, the minimum supported node version is documented nowhere:

- there is no `engines` field in package.json
- there is no doc about it in the readme
- the `.travis.yml` CI config is running a single job rather than testing on multiple versions of node, so this cannot be used to infer support

It would be great to explicitly document the supported versions (especially given that dropping support for a node version is considered semver-breaking).

**Comment by ka-weihe** [comment]
Thank you for the issue.

Fixed in 1f44856e5ce2705c0ff3e517932a362c713cb9b0. I have added engines field to package.json. It works for node versions >= 4.9.1, but versions  below 10 have not been added to CI since jest requires >= 10.
